name: 'Log Action'
description: 'Send log messages using Port'
inputs:
  logMessage:
    description: 'Log message to send'
    required: true
  icon:
    description: 'Icon to use in the log message'
    required: false
    default: '🔔'
  runId:
    description: 'Run ID for the action'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Log Message
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        baseUrl: https://api.getport.io
        operation: PATCH_RUN
        runId: ${{ inputs.runId }}
        logMessage: ${{ inputs.logMessage }}
        icon: ${{ inputs.icon }}
