name: Generate Angular Project

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio'
        required: true
      project_name:
        description: 'proyecto frontend'
        required: true
        default: 'app'

jobs:
  create-and-push:
    name: Create Repository and Push Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}  # Utiliza el token de GitHub para autenticar
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
               -d '{"name":"${{ github.event.inputs.repo_name }}", "private":${{ github.event.inputs.private }}}' \
               https://api.github.com/user/repos

      - name: Checkout repo
        uses: actions/checkout@v3
  
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Instalar Angular CLI
        run: npm install -g @angular/cli
  
      - name: Generar proyecto de Angular
        run: ng new ${{ github.event.inputs.project_name }} --defaults
  
      - run: |
          cd  ${{ github.event.inputs.project_name }}
          git config --global user.email "jhoan.rojas@mercurio.com.co"
          git config --global user.name "JhoanDRojas"
          rm -rf .git/
          git init
          git add .
          git commit -m "Initial commit"
          git branch -M main
  
      - name: Push to new repository
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}
        run: |
          cd  ${{ github.event.inputs.project_name }}
          git remote add origin https://$GITHUB_TOKEN@github.com/JhoanDRojas/$REPO_NAME.git
          git push -f origin main
