name: Create Repository and Push C#

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio'
        required: true
      private:
        description: '¿El repositorio debe ser privado? (true/false)'
        required: true
        default: 'true'

jobs:
  create-and-push:
    name: Create Repository and Push Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}  # Utiliza el token de GitHub para autenticar
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
               -d '{"name":"${{ github.event.inputs.repo_name }}", "private":${{ github.event.inputs.private }}}' \
               https://api.github.com/user/repos
               
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB_ACCTION }}
          fetch-depth: 0
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x' # Asegúrate de usar la versión de .NET que necesites

      - name: Create .NET Project
        run: dotnet new webapp -n ${{ github.event.inputs.repo_name }}

      - name: Create Custom Folder Structure
        run: |
          mkdir -p ${{ github.event.inputs.repo_name }}/Services
          mkdir -p ${{ github.event.inputs.repo_name }}/Models
          mkdir -p ${{ github.event.inputs.repo_name }}/Interfaces

      - run: |
          cd ${{ github.event.inputs.repo_name }}
          git config --global user.email "jhoan.rojas@mercurio.com.co"
          git config --global user.name "JhoanDRojas"
          rm -rf .git/
          git init
          git add .
          git commit -m "Initial commit"
          git branch -M main

      - name: Push to new repository
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}
        run: |
          git remote rm origin
          git remote add origin https://$GITHUB_TOKEN@github.com/JhoanDRojas/$REPO_NAME.git
          git push -f origin main
