name: Create Repository and Push C#

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio'
        required: true
      name_solution: 
        description: 'Nombre de la solución'
        required: true
      name_project: 
        description: 'Nombre del proyecto'
        required: true
      private:
        description: '¿El repositorio debe ser privado? (true/false)'
        required: true
        default: 'true'

jobs:
  create-and-push:
    name: Create Repository and Push Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}  # Utiliza el token de GitHub para autenticar
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
               -d '{"name":"${{ github.event.inputs.repo_name }}", "private":${{ github.event.inputs.private }}}' \
               https://api.github.com/user/repos
               
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB_ACCTION }}
          fetch-depth: 0
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x' # Asegúrate de usar la versión de .NET que necesites

      - name: Crear solución
        run: |
          dotnet new sln -o ${{ github.event.inputs.name_solution }}
      

      - name: Crear proyectos y estructura de carpetas

        run: |
          cd ${{ github.event.inputs.name_solution }}
          mkdir -p src/Application
          mkdir -p src/Domain
          mkdir -p src/Function
          mkdir -p src/Infrastructure/Agents
          mkdir -p src/Infrastructure/ExternalService
          mkdir -p src/Infrastructure/Persistence
          mkdir -p tests
          dotnet new classlib -o src/Application/${{ github.event.inputs.name_project }}.Application
          dotnet new classlib -o src/Domain/${{ github.event.inputs.name_project }}.Domain
          dotnet new classlib -o src/Function/${{ github.event.inputs.name_project }}.Function
          dotnet new classlib -o src/Infrastructure/Agents/${{ github.event.inputs.name_project }}.Infrastructure.Agents
          dotnet new classlib -o src/Infrastructure/ExternalService/${{ github.event.inputs.name_project }}.Infrastructure.ExternalService
          dotnet new classlib -o src/Infrastructure/Persistence/${{ github.event.inputs.name_project }}.Infrastructure.Persistence
          dotnet new xunit -o tests/${{ github.event.inputs.name_project }}.Tests

      - name: Restaurar paquetes NuGet
        run: |
          cd ${{ github.event.inputs.name_solution }}
          dotnet restore
          
      - name: Construir la solución
        run: |
          cd ${{ github.event.inputs.name_solution }}
          dotnet build

      - run: |
          git config --global user.email "jhoan.rojas@mercurio.com.co"
          git config --global user.name "JhoanDRojas"
          rm -rf .git/
          git init
          git add .
          git commit -m "Initial commit"
          git branch -M main

      - name: Push to new repository
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}
        run: |
          git remote add origin https://$GITHUB_TOKEN@github.com/JhoanDRojas/$REPO_NAME.git
          git push -f origin main
