name: Create Repository and Push python domain architectura

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio'
        required: true
      private:
        description: '¿El repositorio debe ser privado? (true/false)'
        required: true
        default: 'true'

jobs:
  create-and-push:
    name: Create Repository and Push Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}  # Utiliza el token de GitHub para autenticar
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
               -d '{"name":"${{ github.event.inputs.repo_name }}", "private":${{ github.event.inputs.private }}}' \
               https://api.github.com/orgs/castor-prueba/repos
               
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB_ACCTION }}
          fetch-depth: 0
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Pwd
        run: pwd
        
      - name: Create folder ${{ github.event.inputs.repo_name }}
        run: |
          mkdir ${{ github.event.inputs.repo_name }}
          cp ./script/script-back-python.py ${{ github.event.inputs.repo_name }}
          cd ${{ github.event.inputs.repo_name }}
          ls -la
      
      - name: Run script
        run: |
          pwd
          cd ${{ github.event.inputs.repo_name }}
          python script-back-python.py
          ls -la

      

      - name: Git
        run: |
          cd ${{ github.event.inputs.repo_name }}
          rm -f script-back-python.py
          git config --global user.email "jhoan.rojas@mercurio.com.co"
          git config --global user.name "JhoanDRojas"
          git init
          git add .
          git commit -m "Initial commit"
          git branch -M main

      - name: Push to new repository
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}
        run: |
          pwd
          ls -la
          cd ${{ github.event.inputs.repo_name }}
          pwd
          git remote add origin https://$GITHUB_TOKEN@github.com/castor-prueba/$REPO_NAME.git
          git push -f origin main
