name: Create Repository and Push python domain architectura

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio'
        required: true
      private:
        description: '¿El repositorio debe ser privado? (true/false)'
        required: true
        default: 'true'

jobs:
  create-and-push:
    name: Create Repository and Push Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACCTION }}  # Utiliza el token de GitHub para autenticar
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
               -d '{"name":"${{ github.event.inputs.repo_name }}", "private":${{ github.event.inputs.private }}}' \
               https://api.github.com/user/repos
               
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB_ACCTION }}
          fetch-depth: 0
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: |
          mkdir ${{ github.event.inputs.repo_name }}
          pwd 
          cd ${{ github.event.inputs.repo_name }}
          python script-back-python.py # Asegúrate de que este script genere los archivos en un directorio específico, por ejemplo 'output/'
